### ISSUE TITLE
Too many Error 429 responses

### ISSUE THREAD

**Issue by cooperjaXC** [ccaoa/google-ece-trends#5]
Starting in early March 2023, the `late2022_datapulls.py` no longer yields results and instead consistently errors with the message below. The backoff factor in `pull_data.py` was instituted in db296cce92475421040d02fa8fd8087db31bd2eb to avoid this error. 

```
Traceback (most recent call last):
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\coding\google-ece-pytrends\py_venv\venv\lib\site-packages\requests\adapters.py", lin
e 489, in send
    resp = conn.urlopen(
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\coding\google-ece-pytrends\py_venv\venv\lib\site-packages\urllib3\connectionpool.py"
, line 878, in urlopen
    return self.urlopen(
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\coding\google-ece-pytrends\py_venv\venv\lib\site-packages\urllib3\connectionpool.py"
, line 878, in urlopen
    return self.urlopen(
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\coding\google-ece-pytrends\py_venv\venv\lib\site-packages\urllib3\connectionpool.py"
, line 878, in urlopen
    return self.urlopen(
  [Previous line repeated 5 more times]
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\coding\google-ece-pytrends\py_venv\venv\lib\site-packages\urllib3\connectionpool.py"
, line 868, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\coding\google-ece-pytrends\py_venv\venv\lib\site-packages\urllib3\util\retry.py", li
ne 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='trends.google.com', port=443): Max retries exceeded with url: /trends/api/explore?hl=en-US&tz=300&req=%7B%22comparisonItem%22%3
A+%5B%7B%22keyword%22%3A+%22%2Fm%2F022hpx%22%2C+%22time%22%3A+%222018-06-03+2022-09-10%22%2C+%22geo%22%3A+%22US%22%7D%5D%2C+%22category%22%3A+0%2C+%22property%22%3A+%22%22%7D (Caused by R
esponseError('too many 429 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\coding\google-ece-pytrends\late2022_datapulls.py", line 326, in <module>
    full_run_gtrends()
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\coding\google-ece-pytrends\late2022_datapulls.py", line 39, in full_run_gtrends
    usa_payload = pull.payload_builder(
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\coding\google-ece-pytrends\pull_data.py", line 141, in payload_builder
    connection_item.build_payload(
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\coding\google-ece-pytrends\py_venv\venv\lib\site-packages\pytrends\request.py", line
 183, in build_payload
    self._tokens()
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\coding\google-ece-pytrends\py_venv\venv\lib\site-packages\pytrends\request.py", line
 189, in _tokens
    widget_dicts = self._get_data(
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\coding\google-ece-pytrends\py_venv\venv\lib\site-packages\pytrends\request.py", line
 138, in _get_data
    response = s.get(url, timeout=self.timeout, cookies=self.cookies,
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\coding\google-ece-pytrends\py_venv\venv\lib\site-packages\requests\sessions.py", lin
e 600, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\coding\google-ece-pytrends\py_venv\venv\lib\site-packages\requests\sessions.py", lin
e 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\coding\google-ece-pytrends\py_venv\venv\lib\site-packages\requests\sessions.py", lin
e 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\coding\google-ece-pytrends\py_venv\venv\lib\site-packages\requests\adapters.py", lin
e 556, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='trends.google.com', port=443): Max retries exceeded with url: /trends/api/explore?hl=en-US&tz=300&req=%7B%22comparisonItem%22%3A+
%5B%7B%22keyword%22%3A+%22%2Fm%2F022hpx%22%2C+%22time%22%3A+%222018-06-03+2022-09-10%22%2C+%22geo%22%3A+%22US%22%7D%5D%2C+%22category%22%3A+0%2C+%22property%22%3A+%22%22%7D (Caused by Res
ponseError('too many 429 error responses'))
```

**Comment by cooperjaXC** [comment]
Has continued to exist throughout the remainder of March 2023. Same error pops up when code is run daily.

Try recalibrating the backoff factor.

**Comment by cooperjaXC** [comment]
[Someone else on StackOverflow](https://stackoverflow.com/questions/75711314/issue-with-pytrends-and-latest-update-of-google-trends-website) started experiencing the same issue around the same time: early March 2023 (Q posed 12 Mar). 

This led me to this [GitHub Issue from 8 March](https://github.com/GeneralMills/pytrends/issues/561). The issue stems from March 2023 updates Google made to security on their end. Looks like Google is [making it harder to scrape trends in an update](https://github.com/GeneralMills/pytrends/issues/561#issuecomment-1462435132), and they can tell who is using browser vs scraping. So, upping the number of `retries` in the `backoff_factor` won't necessarily work; it may be more about your user type classification as a "scraper" vs "legit_user". This may stem from cookies stored on the browser vs what is used in the code, and impersonating the browser cookies seems to be the base of the fix. There was some debate about the right way to fix this (see [this theory](https://github.com/GeneralMills/pytrends/issues/561#issuecomment-1462899426) tested in [an unmerged pull request](https://github.com/GeneralMills/pytrends/pull/563) and [another duplicate issue](https://github.com/GeneralMills/pytrends/issues/566)).

Ultimately, **there was [a fix merged into the GitHub master on 8 April](https://github.com/GeneralMills/pytrends/pull/570)** (only 4 days ago). [PyPi](https://pypi.org/project/pytrends/) was subsequently updated with [`v4.9.1`](https://pypi.org/project/pytrends/4.9.1/) with the fix for this.

Except, surprise! [`v4.9.1` didn't include the merged fix](https://github.com/GeneralMills/pytrends/issues/573#issuecomment-1503689831). So, as of today. they're working on releasing `v4.9.2` that actually fixes this issue. Until then, [one can install from GitHub](https://github.com/GeneralMills/pytrends/issues/573#issuecomment-1503795706) to get this patch included in their installation. I haven't yet tried it, but `v4.9.2` supposedly works. Fingers crossed.

Other examples of people having this issue:
* https://www.reddit.com/r/datasets/comments/12feust/scraping_google_trends_data_in_2023/
    * I contributed my answer above to this thread.
* https://www.reddit.com/r/CodingHelp/comments/rbrg4g/webscraping_with_pytrend_ip_getting_blockederror/

**Comment by cooperjaXC** [comment]
The [`pytrends`](https://github.com/GeneralMills/pytrends) maintainers have now updated their documentation. The previously fixed issue in their code's compatibility with Google's updated API [was not yet in PyPi](https://github.com/GeneralMills/pytrends/issues/573). On 13 April, they fixed this documentation error in [their bump to patch version 4.9.2](https://github.com/GeneralMills/pytrends/commit/220a5b7957de1476f110f89dabde2324aa5985a8). Note that as of now, this documentation bump exists in its own branch outside of `master`. This bump has been applied as [`v4.9.2` in PyPi](https://pypi.org/project/pytrends/4.9.2/). 

In my first test of my code with the updated installation of `pytrends`, this issue was fixed; everything worked flawlessly as expected again. 

Fixed in the development version with commit https://github.com/ccaoa/google-ece-trends/commit/98a4f5387849d55f2ef687a3b6cf01fc8673d1e7. Will patch the `main` branch version to fully close.

**Comment by cooperjaXC** [comment]
Closed with commit https://github.com/ccaoa/google-ece-trends/commit/0b57f6c6914a77143818a7e73afcdd7031aa16c9 to `main`.
