### ISSUE TITLE
Make function to build a full SumStats XLSX from scratch

### ISSUE THREAD

**Issue by cooperjaXC** [ccaoa/google-ece-trends#9]
Closely related to #8, create a function in `summarize.py` that will completely re-start all of the summary sheets from scratch and rebuild them completely. This would source from both a raw data directory and a summary data directory. Once #8 is resolved, it would be just a matter of summarizing the statistics of the newly appended raw data into a `raw_data_records` tab.

The initial work on this was done in 4edaa69385f6046dfea50e2a996feb4303bb5972 with the creation of the `full_summary_run()` function in `summarize.py` . The initial of that function failed, likely a cause of the problems detailed in the append process (#8), but the fix to this enhancement issue needs to also be resilient to the quick export-import of XLSX files issue that plagued the other append process.

Reform the `full_summary_run()` function to be more efficient and fail-safe.

**Comment by cooperjaXC** [comment]
The scope of this has changed slightly with #18 splitting the summary and append processes. The append is handled now in #8, while the summary aspect is here. Specifically, the `full_append_and_summary_run()` function in `summarize.py`.

https://github.com/ccaoa/google-ece-trends/blob/a6c15e98ebd2746c3c43af4343ec4756a683761a/summarize.py#L262-L313

**Comment by cooperjaXC** [comment]
In test on commit 704750f, successful summarize all run with summary only output below (not append all; see https://github.com/ccaoa/google-ece-trends/issues/8#issuecomment-1858614115 for that result):

```
SUMMARIZING CONSOLIDATED RAW DATA...

Summarizing files.
1 / 23 processed:    eugene_time_20200214-20210214_raw_data_records.xlsx
2 / 23 processed:    in_dma_20180603-20220910_raw_data_records.xlsx
3 / 23 processed:    in_time_20180603-20220910_raw_data_records.xlsx
4 / 23 processed:    ky_dma_20180603-20220910_raw_data_records.xlsx
5 / 23 processed:    ky_time_20180603-20220910_raw_data_records.xlsx
6 / 23 processed:    mn_dma_20200214-20210214_raw_data_records.xlsx
7 / 23 processed:    mn_time_20200214-20210214_raw_data_records.xlsx
8 / 23 processed:    oh_dma_20180603-20220910_raw_data_records.xlsx
9 / 23 processed:    oh_time_20180603-20220910_raw_data_records.xlsx
10 / 23 processed:    or_dma_20200214-20210214_raw_data_records.xlsx
11 / 23 processed:    or_time_20200214-20210214_raw_data_records.xlsx
12 / 23 processed:    tx_dma_20210321-20210421_raw_data_records.xlsx
13 / 23 processed:    tx_time_20210321-20210421_raw_data_records.xlsx
14 / 23 processed:    usa_dma_df_20180603-20220910_raw_data_records.xlsx
15 / 23 processed:    usa_rising_qs_20180603-20220910_raw_data_records.xlsx
16 / 23 processed:    usa_states_df_20180603-20220910_raw_data_records.xlsx
17 / 23 processed:    usa_temporal_df_20180603-20220910_raw_data_records.xlsx
18 / 23 processed:    usa_top_qs_20180603-20220910_raw_data_records.xlsx
19 / 23 processed:    valentines_dma_df_20200214-20210214_raw_data_records.xlsx
20 / 23 processed:    valentines_rising_qs_20200214-20210214_raw_data_records.xlsx
21 / 23 processed:    valentines_states_df_20200214-20210214_raw_data_records.xlsx
22 / 23 processed:    valentines_temporal_df_20200214-20210214_raw_data_records.xlsx
23 / 23 processed:    valentines_top_qs_20200214-20210214_raw_data_records.xlsx
---------------------------------------------------------------
Run Time: 0 hr, 1 min, 45 sec.

Process finished with exit code 0
```

**Comment by cooperjaXC** [comment]
Received unexpected error when testing `late2022_datapulls.py` (below). But when data are summarized from the `summarize.full_append_and_summary_run()` command, it succeeds in 30 seconds. Odd. 

```python
Summarizing files.
Traceback (most recent call last):
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\google-ece-pytrends_coding\py_venv\venv\lib\site-packages\pandas\core\nanops.py", li
ne 1603, in _ensure_numeric
    x = float(x)
ValueError: could not convert string to float: '(99.41104304415086, 99.7819394119895)(92.54323003779139, 93.51992785694544)(89.45644361979625, 90.48039848546692)(88.3637082837273, 89.3345
373303078)(88.1501298110479, 89.54109825912754)(88.32281532326012, 89.27718467673988)(87.01267886562559, 87.94872464314633)(82.52915474431161, 83.39365227323223)(81.51205360604678, 82.586
1920079883)(79.5304970938195, 80.49055553775945)(79.08291849349058, 79.90655519071996)(77.70602070453342, 78.5115231551157)(77.52955277498772, 78.26693845308246)(77.42101736243765, 78.291
26333931674)(76.21586668120942, 77.02623858194848)(75.75054272323054, 76.63542218905017)(75.73459280597999, 76.55312649226562)(73.62128851779266, 74.40678165764592)(73.32522652814137, 74.
17652785782354)(72.53390907379404, 73.48012601392526)(71.92169263949754, 72.69585122015158)(71.4330049107607, 72.34243368573053)(70.47660998924776, 71.17953036162943)(70.02891057275414, 7
1.03775609391252)(69.00529718542184, 69.79470281457817)(68.76095942314345, 69.54781250668111)(68.7399780213001, 69.48458338220867)(68.71328872140089, 69.39197443649385)(68.26233124259765,
 69.02889682757778)(67.51329689731948, 68.22003643601384)(66.18598186685169, 66.92980760683251)(65.93929956281757, 66.83263026174383)(65.89762045462598, 66.58659007168981)(64.338519470247
46, 65.03691912624376)(63.82872839865614, 64.50109616274737)(63.49150234391573, 64.19270818240007)(63.26946652075998, 64.0287790932751)(62.17979974263084, 62.91493709947442)(61.4434900324
0079, 62.107387160581666)(61.33141085769073, 62.14227335283559)(60.60999170760647, 61.26369250291985)(57.61003557697883, 58.22856091424924)(55.64625516208975, 56.27655185545411)(54.257110
827852635, 54.87973127741052)(54.242108338365924, 54.82455832830074)(54.24047393187208, 54.770052383917395)(53.40770247890165, 54.234402784256254)(51.322181054942554, 51.89887157663639)(4
7.84132419072132, 48.390254756647096)(47.59404166246384, 48.125256583150204)(40.48424434548318, 40.96136968960454)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\google-ece-pytrends_coding\py_venv\venv\lib\site-packages\pandas\core\nanops.py", li
ne 1607, in _ensure_numeric
    x = complex(x)
ValueError: complex() arg is a malformed string

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\google-ece-pytrends_coding\late2022_datapulls.py", line 375, in <module>
    full_run_gtrends(pull_trends_data=True)
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\google-ece-pytrends_coding\late2022_datapulls.py", line 365, in full_run_gtrends
    agg.summarize_collected_data(targ_sumfiles_listdir, suppress_prints=False)
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\google-ece-pytrends_coding\summarize.py", line 254, in summarize_collected_data
    calc_sumstats(sd)
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\google-ece-pytrends_coding\summarize.py", line 161, in calc_sumstats
    sumstats_df[gtis_average_field] = sumstats_df[uoa_col].apply(lambda d: raw_data_df[d].mean())
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\google-ece-pytrends_coding\py_venv\venv\lib\site-packages\pandas\core\series.py", li
ne 4357, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\google-ece-pytrends_coding\py_venv\venv\lib\site-packages\pandas\core\apply.py", lin
e 1043, in apply
    return self.apply_standard()
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\google-ece-pytrends_coding\py_venv\venv\lib\site-packages\pandas\core\apply.py", lin
e 1098, in apply_standard
    mapped = lib.map_infer(
  File "pandas\_libs\lib.pyx", line 2859, in pandas._libs.lib.map_infer
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\google-ece-pytrends_coding\summarize.py", line 161, in <lambda>
    sumstats_df[gtis_average_field] = sumstats_df[uoa_col].apply(lambda d: raw_data_df[d].mean())
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\google-ece-pytrends_coding\py_venv\venv\lib\site-packages\pandas\core\generic.py", l
ine 10751, in mean
    return NDFrame.mean(self, axis, skipna, level, numeric_only, **kwargs)
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\google-ece-pytrends_coding\py_venv\venv\lib\site-packages\pandas\core\generic.py", l
ine 10369, in mean
    return self._stat_function(
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\google-ece-pytrends_coding\py_venv\venv\lib\site-packages\pandas\core\generic.py", l
ine 10354, in _stat_function
    return self._reduce(
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\google-ece-pytrends_coding\py_venv\venv\lib\site-packages\pandas\core\series.py", li
ne 4392, in _reduce
    return op(delegate, skipna=skipna, **kwds)
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\google-ece-pytrends_coding\py_venv\venv\lib\site-packages\pandas\core\nanops.py", li
ne 94, in _f
    return f(*args, **kwargs)
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\google-ece-pytrends_coding\py_venv\venv\lib\site-packages\pandas\core\nanops.py", li
ne 156, in f
    result = alt(values, axis=axis, skipna=skipna, **kwds)
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\google-ece-pytrends_coding\py_venv\venv\lib\site-packages\pandas\core\nanops.py", li
ne 411, in new_func
    result = func(values, axis=axis, skipna=skipna, mask=mask, **kwargs)
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\google-ece-pytrends_coding\py_venv\venv\lib\site-packages\pandas\core\nanops.py", li
ne 666, in nanmean
    the_sum = _ensure_numeric(values.sum(axis, dtype=dtype_sum))
  File "C:\Users\Jacob.Cooper\OneDrive - NACCRRA\Documents\ArcGIS\Projects\GoogleTrends_Demand_HomeDir\google-ece-pytrends_coding\py_venv\venv\lib\site-packages\pandas\core\nanops.py", li
ne 1610, in _ensure_numeric
    raise TypeError(f"Could not convert {x} to numeric") from err
TypeError: Could not convert (99.41104304415086, 99.7819394119895)(92.54323003779139, 93.51992785694544)(89.45644361979625, 90.48039848546692)(88.3637082837273, 89.3345373303078)(88.15012
98110479, 89.54109825912754)(88.32281532326012, 89.27718467673988)(87.01267886562559, 87.94872464314633)(82.52915474431161, 83.39365227323223)(81.51205360604678, 82.5861920079883)(79.5304
970938195, 80.49055553775945)(79.08291849349058, 79.90655519071996)(77.70602070453342, 78.5115231551157)(77.52955277498772, 78.26693845308246)(77.42101736243765, 78.29126333931674)(76.215
86668120942, 77.02623858194848)(75.75054272323054, 76.63542218905017)(75.73459280597999, 76.55312649226562)(73.62128851779266, 74.40678165764592)(73.32522652814137, 74.17652785782354)(72.
53390907379404, 73.48012601392526)(71.92169263949754, 72.69585122015158)(71.4330049107607, 72.34243368573053)(70.47660998924776, 71.17953036162943)(70.02891057275414, 71.03775609391252)(6
9.00529718542184, 69.79470281457817)(68.76095942314345, 69.54781250668111)(68.7399780213001, 69.48458338220867)(68.71328872140089, 69.39197443649385)(68.26233124259765, 69.02889682757778)
(67.51329689731948, 68.22003643601384)(66.18598186685169, 66.92980760683251)(65.93929956281757, 66.83263026174383)(65.89762045462598, 66.58659007168981)(64.33851947024746, 65.036919126243
76)(63.82872839865614, 64.50109616274737)(63.49150234391573, 64.19270818240007)(63.26946652075998, 64.0287790932751)(62.17979974263084, 62.91493709947442)(61.44349003240079, 62.1073871605
81666)(61.33141085769073, 62.14227335283559)(60.60999170760647, 61.26369250291985)(57.61003557697883, 58.22856091424924)(55.64625516208975, 56.27655185545411)(54.257110827852635, 54.87973
127741052)(54.242108338365924, 54.82455832830074)(54.24047393187208, 54.770052383917395)(53.40770247890165, 54.234402784256254)(51.322181054942554, 51.89887157663639)(47.84132419072132, 4
8.390254756647096)(47.59404166246384, 48.125256583150204)(40.48424434548318, 40.96136968960454) to numeric
```
